### ISSUE TITLE
test higher current limits for thrust motors for max acceleration

### ISSUE THREAD

**Issue by jheidegger** [Team3176/Code_2024#18]
Currently limited to 40 Amps
test at both 60 and 80 amps and see how it performs. 
Might need to add a closedloop ramp rate

Modify the SwervePodIOFalconSpark.java to increase the current limit

**Comment by char3176** [comment]
Can Milly zoom w/ Jon?

**Comment by char3176** [comment]
@jheidegger may I inquire progress/status of this from Thur night?

**Comment by jheidegger** [comment]
Have code ready to test on the robot with 60 amp limits. May go up to 80 if we don't trip the breakers

**Comment by char3176** [comment]
Milly, lets also retest this Mon night.

**Comment by char3176** [comment]
Works.  Almost brownout at one small point. We will monitor to see if need to change back from 60Amps to 40Amps.  Milly says Yay!
