### ISSUE TITLE
Investigate why Blinkin stopped working.  Begin by HW people taking apart and taking photos of PCB, looking for discolorations or deformations like melting.  Possibly consider beginning to develop our own LED library like the Blinken one that uses addressibleLEDs directly instead of the Blinkin.

### ISSUE THREAD

**Issue by char3176** [Team3176/Code_2024#19]

**Comment by SamuelWillman** [comment]
There may already be an adressableLED library on one of the laptops.

**Comment by SamuelWillman** [comment]
At least, we started it on the laptops, I dont know if we actually kept it or not.

**Comment by SamuelWillman** [comment]
There are people using the robot, when we can acess it ourselves, we will have to factory reset the blinkin and hope that it helps.

**Comment by char3176** [comment]
While using the robot later that evening, the leds suddenly came back.  We are clearly experiencing problems that others on ChiefDelphi have also reported.

@SamuelWillman I believe we should proceed to develop our own library using addressibleLEDs that replicates the Blinkin capabilities.

Does anyone object?

**Comment by char3176** [comment]
I will wait for @SamuelWillman's input, but at present I think we are ready to close this "issue" and open a new one that involves building a library that replicates the Blinkin pattens.  

Any last input/comments @SamuelWillman, or are we good to close this "issue"?  And if we are good to close, I'm going to walk you thru how to do that at Fri meeting.

**Comment by char3176** [comment]
I'm creating a new issue for development of a library using addressibleLEDs that replicates the Blinkin functionality.

**Comment by char3176** [comment]
#41

**Comment by char3176** [comment]
#41
