### ISSUE TITLE
Upgrade photon vision install on Orange Pi's

### ISSUE THREAD

**Issue by char3176** [Team3176/Code_2024#21]

**Comment by jheidegger** [comment]
Upgrade the vendor dep as well for the code

**Comment by char3176** [comment]
Liam McNeely please update on progress here.  Begin to do this every night, please.

**Comment by Marbledata** [comment]
Three pi’s have been updated, tomorrow I’ll bring the travel router and see if I can change the jar file, currently I am reflashing the card. Only pi left is on the robot

**Comment by char3176** [comment]
Liam and Faith, you may now take the last Orange Pi on the side of the bot and upgrade it, then close this issue. Yay!

**Comment by Marbledata** [comment]
Understood

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
