### ISSUE TITLE
Implement PID on climb in roll on just 1 arm using NavX roll value.

### ISSUE THREAD

**Issue by char3176** [Team3176/Code_2024#26]

**Comment by jheidegger** [comment]
Take a look in drivetrain there are the functions
getChassisRoll()
getChassisPitch()

That can be useful for getting the values

**Comment by char3176** [comment]
@222003791 was able to get motor linked to gyro value.  However appears to be continuous, ie not isolated to running only when xbox button pressed.  That is next problem to solve.  After that, we need to make sure motor is going in opposite directions when board tilted in opposite directions.  Once these are resolved, we are ready to attempt to do it with 2 arms.

**Comment by char3176** [comment]
Was continuous b/c was being called in @periodic.  Still experiencing issues with linking to xbox button.

**Comment by char3176** [comment]
Climb on 1 arm completed.  Prototype for Climb on 2 arm is in PR 65
