### ISSUE TITLE
Fix three cameras with broken JST wires.

### ISSUE THREAD

**Issue by char3176** [Team3176/Code_2024#29]

**Comment by WolfeeZed** [comment]
Approx 3.6 mm height (Outside)
Approx 7.5 mm width (outside)
Approx 6.5mm width (inside) 
Approx 3 mm length (inside)
![ACA61090-7BAF-49B2-8154-D49E18456464](https://github.com/Team3176/Code_2024/assets/71674445/98a39236-db77-49bc-af47-0164f571bb03)


Do not have the correct size of JST housing, we need more ordered

**Comment by char3176** [comment]
I think it might be a JST-ZH 4 pin female connector.  I've placed order for them.  Should have in time for Monday meeting to try.

**Comment by jheidegger** [comment]
https://www.chiefdelphi.com/t/frc-6328-mechanical-advantage-2024-build-thread/442736/151?u=jheidegger
I think Chris is right as described in this thread

**Comment by char3176** [comment]
Yeah, they arrived and they fit perfect.  However they came with precrimp leads, so we'll need to splice those onto the existing wire and heatshrink, Braeden.  Can do Mon night if you are at meeting.

**Comment by WolfeeZed** [comment]
Yep, I’ll be there tonight and I can do it right after I’m done reconnecting the wires on the practice defense bot to the PDH

**Comment by WolfeeZed** [comment]
All 3 camera wires have been fixed and cases have been added to them for future use.
