### ISSUE TITLE
drivetrain FOC High Frequency Odom

### ISSUE THREAD

**Issue by jheidegger** [Team3176/Code_2024#37]

**Comment by char3176** [comment]
Milly, we'll test this Monday night.

**Comment by jheidegger** [comment]
If we start to run into errors we can go back to [this](https://github.com/Team3176/Code_2024/commit/47b32874bd08ceff68fd7741209fb83772350825) commit which is only switching to FOC

**Comment by char3176** [comment]
Thur:  fix canbus quickly then retest FOC code.  Expect it to work.  Then proceed to bot rewire of can and sensors.

**Comment by char3176** [comment]
Functioning correctly.

Merged into integration branch 20240315 14:35
