### ISSUE TITLE
Develop our own LED library using addressableLED that replicates the Blinkin functionality

### ISSUE THREAD

**Issue by char3176** [Team3176/Code_2024#41]

**Comment by char3176** [comment]
I'm thinking we start by stealing Mechanical Advantages Led class and use it as the beginning base for our code.   

`https://github.com/Mechanical-Advantage/RobotCode2024/blob/main/src/main/java/org/littletonrobotics/frc2024/subsystems/leds/Leds.java`

It provides nearly all the base fxnality I want.  Thoughts, Sam?

**Comment by SamuelWillman** [comment]
Should be fine to start with

**Comment by jheidegger** [comment]
Implemented for State. Addressable LEDS looked great. new issue should be opened with specific goals
