### ISSUE TITLE
Test Swede_2024 on Swede bot

### ISSUE THREAD

**Issue by char3176** [Team3176/Code_2024#42]
Deploy Swede_2024 repo code to Swede bot and test.  Fix values for bot size (aka transforms/offsets of pods from bot center)

Start here:  https://github.com/Team3176/Swede_2024

**Comment by char3176** [comment]
The continues work from #30

**Comment by jheidegger** [comment]
test the defense branch of Code_2024 that adds the ROBOT_DEFENSE robot type within Constants. 

This lets us continue drivetrain development in one unified codebase.

**Comment by char3176** [comment]
Tested in Defense branch and resolved by PR#52
