### ISSUE TITLE
Rewire sensors & possibly canbus on comp bot for Washington

### ISSUE THREAD

**Issue by char3176** [Team3176/Code_2024#46]

**Comment by char3176** [comment]
We will likely begin the rewire of sensors and canbus on Thur (Mar 14).

**Comment by char3176** [comment]
Dewiring done on Thur Mar 14.  Rewiring of canbus began Mar 15 and ~70-75% complete by end of meeting.

**Comment by char3176** [comment]
Canbus successfully wired, with branch points for intake and conveyor.  Most of sensor wires with new sheathed cabling created and mounted on Rio side.  Will crimp and attach to sensors once Conveyor and Intake remounted.

**Comment by jheidegger** [comment]
closing this specific issue since it relates to washington. Wiring will be an ongoing discussion
