### ISSUE TITLE
Conveyor Tuning Speeds

### ISSUE THREAD

**Issue by jheidegger** [Team3176/Code_2024#66]
"Intake process would as follows:
-4 Bar down and intake spinning
-Conveyor spinning at speedA
-Note triggers LaserCAN1
-Intake returns and Conveyor slows to SpeedB
-Note Triggers LaserCAN2
-Conveyor stops (edited) " - from Ben

**Comment by char3176** [comment]
@jheidegger Logic has mildly changed.  LzrCAN2 is now "in front" of LzrCAN1, therefore LzrCAN2 has to trip twice (once for each front of note, and second for back of note) before stopping conveyor.

**Comment by jheidegger** [comment]
reminder to check direction and invert motor config if needed. Positive is note going towards shooter, negative is note going out towards intake

**Comment by jheidegger** [comment]
isLaser2 and isLaser1 are exposed for the intakeNote logic in superstructure

**Comment by jheidegger** [comment]
Conveyor logic is implemented with linebreaks and worked at wash and state
